[build-system]
requires = ["scikit-build-core", "pybind11", "tree-sitter", "tree-sitter-cpp"]
build-backend = "scikit_build_core.build"

[project]
name = "Beavs5"
version = "0.0.1"
description = "Firmware and simulation for Beav5"
readme = "README.md"
dependencies = []

[project.optional-dependencies]
test = ["pytest", "parse", "matplotlib", "bayesian-optimization"]

[tool.setuptools]
packages = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
